import 'package:ex_app/data/exercise_model.dart';

List<Exercise> advancedExercises = [
  Exercise(
    id: 0,
    name: 'Arm Circles',
    imagePath: 'assets/gif/Advanced/Arm_Circles.gif',
    time: '60',
    duration: const Duration(seconds: 60),
    steps: [
      'Seated in a chair, lift your right foot off the floor and slowly rotate your foot 5 times to the right and then 5 times to the left.',
      'Repeat with the left foot.',
    ],
  ),
  Exercise(
    id: 1,
    name: 'Ankle Circles',
    imagePath: 'assets/gif/Advanced/Ankle_circles.gif',
    time: '60',
    duration: const Duration(seconds: 60),
    steps: [
      'Stand straight with your feet shoulder-width apart. Raise and extend your arms to the sides without bending the elbows.',
      'Slowly rotate your arms forward, making small circles of about 1 foot in diameter.',
      'Complete 30 seconds in one direction and then switch, rotating backward.',
    ],
  ),
  Exercise(
    id: 2,
    name: 'Seated Forward Bend',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Seated_Forward_Bend.gif',
    time: '60',
    steps: [
      'Sit with your legs extended in front of you. Lift your arms.',
      'Hinge at your hips to fold forward. Place your hands on your legs or the floor.',
      'Hold this position for up to 10 seconds. Repeat.',
    ],
  ),
  Exercise(
    id: 3,
    name: 'Standing Forward Bend',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Standing_Forward_Bend.gif',
    time: '60',
    steps: [
      'From a standing position, slowly hinge at your hips to bend forward.',
      'Lengthen your spine, and allow your head to fall heavy toward the floor, keeping a slight bend in your knees.',
      'Place your hands on the floor. Hold this position for 10 seconds. Repeat.',
    ],
  ),
  Exercise(
    id: 4,
    name: 'Standing March',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Standing_March.gif',
    time: '60',
    steps: [
      'Stand with feet shoulder-width apart, hands on hips, and knees close together.',
      'Squeeze abs to lift one knee up, keeping bottom of your foot parallel with the floor.',
      'Lower your knee back down. Repeat on the other side.',
    ],
  ),
  Exercise(
    id: 5,
    name: 'Tree Pose',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Tree_Pose.gif',
    time: '60',
    steps: [
      'From standing, shift your weight onto your right foot. Place your hands in any comfortable position.',
      'Position your left foot to the side with your heel lifted, place the sole of your foot against your thigh.',
      'Hold for up to 30 seconds. Then do the opposite side.',
    ],
  ),
  Exercise(
    id: 6,
    name: 'Single Leg Deadlift',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Single_Leg_Deadlift.gif',
    time: '60',
    steps: [
      'Stand with your arms at your sides, with your right foot a few inches off the floor. Keeping your left knee very slightly bent, lean forward onto your left leg, raising your right leg behind you and reaching toward the floor with your hands. ',
      'Your head, back and right leg should form a straight line, parallel to the ground.',
      'Hold for a second and slowly return to the start position. Then switch sides.',
    ],
  ),
  Exercise(
    id: 7,
    name: 'Reverse Lunges',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Reverse_Lunges.gif',
    time: '60',
    steps: [
      'Stand upright with your hands on your hips. Step backward with your right leg, dropping your right knee toward the ground and bending your left knee to 90 degrees. ',
      'Make sure your left knee is stacked directly over your ankle, and not moving to either side. ',
      'Press through your left heel and return your right leg to the start position. Repeat repetitions, then switch sides.',
    ],
  ),
  Exercise(
    id: 8,
    name: 'Double Leg Hopes',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Double_leg_hops.gif',
    time: '60',
    steps: [
      'Stand straight with your arms at your sides.',
      'Jump up straight, raising your arms as you lift.',
      'Repeat 10 times.',
    ],
  ),
  Exercise(
    id: 9,
    name: 'High Knee Twist',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/high_knee_twist.gif',
    time: '60',
    steps: [
      'Start with your right foot extended back behind you and your hands together, reaching up and out. Keep the weight in your left foot.',
      'Drive your right knee up and toward your chest as you bring your hands down and twist your upper body to the right.',
      'Re-extend your hands up and out while you tap your right foot back behind you. Repeat, continuing for 30 seconds. Then repeat on the left side for 30 seconds.',
    ],
  ),
  Exercise(
    id: 10,
    name: 'Jumping Jacks',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Jumping_Jacks.gif',
    time: '60',
    steps: [
      'Start with feet together and arms down by the side. Bend your knees slightly.',
      'Jump your feet out to the side and raise your arms overhead simultaneously.',
      'Immediately jump back to starting position. And repeat.',
    ],
  ),
  Exercise(
    id: 11,
    name: 'Squat Jumps',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Advanced/Squat_Jumps.gif',
    time: '60',
    steps: [
      'Stand with the feet hip-width apart and arms at the sides. Bend at the knees to squat. ',
      'From the squat position, jump in the air and extend the hips until the body is straight.',
      'Land softly on the balls of the feet. Repeat using different arm movements to adjust the difficulty.',
    ],
  ),
];
