import 'package:ex_app/data/exercise_model.dart';

List<Exercise> beginnerExercises = [
  Exercise(
    id: 0,
    name: 'Neck Stretch',
    imagePath: 'assets/gif/Beginner/Neck_Stretch.gif',
    time: '60',
    duration: const Duration(seconds: 60),
    steps: [
      'Stand with your feet flat on the floor, shoulder-width apart. Keep your hands relaxed at your sides.',
      'Turn your head slowly to the right. Don’t tip your head forward or backward. Stop when you feel a slight stretch. Hold for 10 to 30 seconds.',
      'Now turn to the left. Hold for 10 to 30 seconds.',
    ],
  ),
  Exercise(
    id: 1,
    name: 'Head Tilts',
    imagePath: 'assets/gif/Beginner/Head_Tilts.gif',
    time: '60',
    duration: const Duration(seconds: 60),
    steps: [
      'Relax and lean your head forward. Slowly roll toward one side and hold for 10 seconds.',
      'Repeat on left side.',
      'Relax again and lift your chin back to starting position.',
    ],
  ),
  Exercise(
    id: 2,
    name: 'Upper Trap Stretch',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Upper_Trap_Stretch.gif',
    time: '60',
    steps: [
      'Gently pull your head toward each shoulder until a light stretch is felt.',
      'Hold the pose for 10 to 15 seconds.',
      'Alternate once on each side.',
    ],
  ),
  Exercise(
    id: 3,
    name: 'Raised Hands Pose',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Raised_Hands_Pose.gif',
    time: '60',
    steps: [
      'On an inhalation, raise your arms toward the ceiling.',
      'Hold the pose for 2 seconds. Put down your arms.',
      'Repeat the step 10 times.',
    ],
  ),
  Exercise(
    id: 4,
    name: 'Shoulder Shrug',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Shoulder_Shrug.gif',
    time: '60',
    steps: [
      'Raise both shoulders at once up toward the ears.',
      'Drop them and repeat 15 times.',
    ],
  ),
  Exercise(
    id: 5,
    name: 'Reach Back',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Reach_Back.gif',
    time: '60',
    steps: [
      'Sit with spine straight, feet planted firmly on the ground. Reach behind you and interlace your hands. ',
      'Roll your shoulders up and back, moving your shoulder blades down your back. Hold your hands tightly, gently straighten your arms and open up your upper back.',
      'After 3 deep breaths, release your clasp and return to neutral. Repeat this 10 times.',
    ],
  ),
  Exercise(
    id: 6,
    name: 'Upper Body Stretch',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Upper_Body_Stretch.gif',
    time: '60',
    steps: [
      '1Clasp hands together above the head with palms facing outward.',
      'Push your arms up, stretching upward. ',
      'Hold the pose for 10 to 30 seconds. Repeat 6 times.',
    ],
  ),
  Exercise(
    id: 7,
    name: 'Triceps Stretch',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Triceps_Stretch.gif',
    time: '60',
    steps: [
      'Raise your arm and bend it so that your hand reaches toward the opposite side.',
      'Use your other hand and pull the elbow toward your head.',
      'Hold for 10 to 30 seconds. Repeat on the other side.',
    ],
  ),
  Exercise(
    id: 8,
    name: 'Forward Stretch',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Forward_Stretch.gif',
    time: '60',
    steps: [
      'Clasp your hands in front of you and lower your head in line with your arms.',
      'Press forward and hold for 10 to 30 seconds.',
    ],
  ),
  Exercise(
    id: 9,
    name: 'Overhead Reach',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Overhead_Reach.gif',
    time: '60',
    steps: [
      'Extend each arm overhead. Reach to the opposite side.',
      'Hold for 10 to 30 seconds.',
      'Repeat on the other side.',
    ],
  ),
  Exercise(
    id: 10,
    name: 'Gentle Twist',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Gentle_Twist.gif',
    time: '60',
    steps: [
      'Start with your feet firmly planted on the floor. As you inhale, press down into your seat, sit up straight and lift your arms up overhead.',
      'As you exhale, turn gently to your right, placing your left hand on your right knee and your right hand on the chair. ',
      'Take 3 to 5 deep breaths before gently releasing the twist and doing it on the other side. Alternate so you stretch at least twice on each side.',
    ],
  ),
  Exercise(
    id: 11,
    name: 'Toe taps',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Toe_Taps.gif',
    time: '60',
    steps: [
      'Sitting in a chair and keeping your heels on the floor.',
      'Lift your toes high enough that you can feel the muscles along your shin working. ',
      'Repeat 20 times.',
    ],
  ),
  Exercise(
    id: 12,
    name: 'Heel Raises',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Heel_Raises.gif',
    time: '60',
    steps: [
      'Sitting in a chair, keep your toes and the balls of your feet on the floor and lift your heels.',
      'Repeat 20 times.',
    ],
  ),
  Exercise(
    id: 13,
    name: 'Ankle Rotations',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Ankle_Rotations.gif',
    time: '60',
    steps: [
      'Seated in a chair, lift your right foot off the floor and slowly rotate your foot 5 times to the right and then 5 times to the left.',
      'Repeat with the left foot.',
    ],
  ),
  Exercise(
    id: 14,
    name: 'Knee Lift',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Beginner/Knee_Lift.gif',
    time: '60',
    steps: [
      'Seated in a chair, hold the sides of the chair with your arms and lift your leg. ',
      'Pause for 3 seconds and slowly lower your leg.',
      'Complete 8 to 12 repetitions and then repeat with the opposite leg.',
    ],
  ),
];
