import 'package:ex_app/data/exercise_model.dart';

List<Exercise> intermediateExercises = [
  Exercise(
    id: 0,
    name: 'Chest Stretch',
    imagePath: 'assets/gif/Intermediate/Chest_Stretch.gif',
    time: '60',
    duration: const Duration(seconds: 60),
    steps: [
      'Stand straight, with the legs shoulder-width apart. Both hands reach behind the body and interlace the fingers with the palms pointing upward.',
      'Keeping the back and arms straight, extending your chest forward pull your shoulders back. ',
      'Stay for 10 – 15 seconds, then release it.',
    ],
  ),
  Exercise(
    id: 1,
    name: 'Shifting Weight',
    imagePath: 'assets/gif/Intermediate/Shifting_Weight.gif',
    time: '60',
    duration: const Duration(seconds: 60),
    steps: [
      'Stand with your feet hip-width apart and your weight evenly distributed on both feet.',
      'Relax your hands at your sides. Shift your weight on to your right side, then lift your left foot.',
      'Hold for 10 seconds. Return to the starting position and repeat with the opposite leg.',
    ],
  ),
  Exercise(
    id: 2,
    name: 'One Leg Balance',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/One_Leg_Balance.gif',
    time: '60',
    steps: [
      'When standing, put your hands on your hips, keep your feet hip-width apart.',
      'Lift your left foot from the floor, bend your knees, and lift your heels back. ',
      'Hold for 10-30 seconds. Return to the starting position and repeat with the other leg. Repeat 3 times.',
    ],
  ),
  Exercise(
    id: 3,
    name: 'Hip Extension',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Hip_Extension.gif',
    time: '60',
    steps: [
      'Stand upright with the legs straight and the feet shoulder-width apart. Extend both arms out in front and hold on to a chair for support.',
      'Keeping the right leg straight, lift the left leg backward without bending the knee. Lift the leg as far as possible, then clench the buttock tightly.',
      'Hold the position for 5 seconds. Repeat this stretch 5–10 times on each leg. ',
    ],
  ),
  Exercise(
    id: 4,
    name: 'Heel to Buttock Exercise',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Heel_to_Buttock-Exercise.gif',
    time: '60',
    steps: [
      'Stand upright with the legs straight and the feet shoulder-width apart. ',
      'Bending the left knee, bring the heel up toward the left buttock with the top of the foot facing the floor. ',
      'Slowly lower the leg and return to the starting position. Repeat the exercise on the opposite side.',
    ],
  ),
  Exercise(
    id: 5,
    name: 'Hip Flexion',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Hip_Flexion.gif',
    time: '60',
    steps: [
      'Stand upright. Extend one arm out to the side and hold on to a wall for support.',
      'Slowly raise the right knee to the level of the hip or as far as is comfortable while keeping the left leg straight.',
      'Only hold this position for a second before placing the left foot back on the floor. Repeat with the left knee.',
    ],
  ),
  Exercise(
    id: 6,
    name: 'Chair Stand Exercise',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Chair_Stand_Exercise.gif',
    time: '60',
    steps: [
      'Sitting on the front part of the seat, bend the knees and place the feet flat on the floor. ',
      'Cross the arms, placing each hand on the opposite shoulder. Lean the upper body forward again and then slowly stand up. ',
      'Keep the back, shoulders, and head straight while doing this. Slowly sit back down and return to the original position.',
    ],
  ),
  Exercise(
    id: 7,
    name: 'Lateral Shuffles',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Lateral_Shuffles.gif',
    time: '60',
    steps: [
      'Start on one end of a room and squat slightly.',
      'Shuffle toward the other side of the room, with the feet meeting together before shuffling out and forward again.',
      'Pick up speed and increase the squat depth to increase the exercise intensity.',
    ],
  ),
  Exercise(
    id: 8,
    name: 'Jogging in Place',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Jogging_in_Place.gif',
    time: '60',
    steps: [
      'bounce lightly from one foot to the other. At the same time, swing the arms from side to side.',
    ],
  ),
  Exercise(
    id: 9,
    name: 'Wall Bicep Stretch',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Wall_Bicep_Stretch.gif',
    time: '60',
    steps: [
      'Press your left palm against a wall or sturdy object. Slowly turn your body away from the wall.',
      'Feel the stretch in your chest, shoulder, and arm.',
      'Hold this position for up to 30 seconds. Repeat on the opposite side.',
    ],
  ),
  Exercise(
    id: 10,
    name: 'Wall Pushups',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Wall_Pushups.gif',
    time: '60',
    steps: [
      'Stand about 3 feet away from a wall, facing the wall, with your feet shoulder-width apart.',
      'Lean forward and place your hands flat on the wall, in line with your shoulders. Spine straight, not sagging or arched.',
      'Lower your body toward the wall and then push back. Repeat 8 times.',
    ],
  ),
  Exercise(
    id: 11,
    name: 'Wall Squat',
    duration: const Duration(seconds: 60),
    imagePath: 'assets/gif/Intermediate/Wall_Squat.gif',
    time: '60',
    steps: [
      'Stand with the head, shoulders, back, and hips flat against a wall. Step both feet out about 24 inches away from the wall.',
      'Keep your feet shoulder-width apart. Slide the back down the wall slowly until the body is just above a normal sitting position.',
      'Hold for 5 seconds and then slide back up. Repeat 8 times.',
    ],
  ),
];
